/*
 * generated by Xtext
 */
package edu.cmu.sei.eebm;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EEBMRuntimeModule extends edu.cmu.sei.eebm.AbstractEEBMRuntimeModule {

}
