/*
 * generated by Xtext
 */
package edu.cmu.sei.eebm.serializer;

import com.google.inject.Inject;
import edu.cmu.sei.eebm.services.EEBMGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class EEBMSyntacticSequencer extends AbstractSyntacticSequencer {

	protected EEBMGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Decision_OptionsKeyword_3_4_0_a;
	protected AbstractElementAlias match_Decision_OptionsKeyword_3_4_0_p;
	protected AbstractElementAlias match_Goal_RightSquareBracketKeyword_2_1_a;
	protected AbstractElementAlias match_Goal_RightSquareBracketKeyword_2_1_p;
	protected AbstractElementAlias match_Option_PriorityKeyword_4_3_0_a;
	protected AbstractElementAlias match_Option___PriorityKeyword_4_3_0_a_ConflictsKeyword_4_2_0__q;
	protected AbstractElementAlias match_Option___PriorityKeyword_4_3_0_a_RefinesKeyword_4_1_0__q;
	protected AbstractElementAlias match_XBlockExpression_SemicolonKeyword_2_1_q;
	protected AbstractElementAlias match_XExpressionInClosure_SemicolonKeyword_1_1_q;
	protected AbstractElementAlias match_XFunctionTypeRef___LeftParenthesisKeyword_0_0_RightParenthesisKeyword_0_2__q;
	protected AbstractElementAlias match_XImportDeclaration_SemicolonKeyword_2_q;
	protected AbstractElementAlias match_XParenthesizedExpression_LeftParenthesisKeyword_0_a;
	protected AbstractElementAlias match_XParenthesizedExpression_LeftParenthesisKeyword_0_p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (EEBMGrammarAccess) access;
		match_Decision_OptionsKeyword_3_4_0_a = new TokenAlias(true, true, grammarAccess.getDecisionAccess().getOptionsKeyword_3_4_0());
		match_Decision_OptionsKeyword_3_4_0_p = new TokenAlias(true, false, grammarAccess.getDecisionAccess().getOptionsKeyword_3_4_0());
		match_Goal_RightSquareBracketKeyword_2_1_a = new TokenAlias(true, true, grammarAccess.getGoalAccess().getRightSquareBracketKeyword_2_1());
		match_Goal_RightSquareBracketKeyword_2_1_p = new TokenAlias(true, false, grammarAccess.getGoalAccess().getRightSquareBracketKeyword_2_1());
		match_Option_PriorityKeyword_4_3_0_a = new TokenAlias(true, true, grammarAccess.getOptionAccess().getPriorityKeyword_4_3_0());
		match_Option___PriorityKeyword_4_3_0_a_ConflictsKeyword_4_2_0__q = new GroupAlias(false, true, new TokenAlias(true, true, grammarAccess.getOptionAccess().getPriorityKeyword_4_3_0()), new TokenAlias(false, false, grammarAccess.getOptionAccess().getConflictsKeyword_4_2_0()));
		match_Option___PriorityKeyword_4_3_0_a_RefinesKeyword_4_1_0__q = new GroupAlias(false, true, new TokenAlias(true, true, grammarAccess.getOptionAccess().getPriorityKeyword_4_3_0()), new TokenAlias(false, false, grammarAccess.getOptionAccess().getRefinesKeyword_4_1_0()));
		match_XBlockExpression_SemicolonKeyword_2_1_q = new TokenAlias(false, true, grammarAccess.getXBlockExpressionAccess().getSemicolonKeyword_2_1());
		match_XExpressionInClosure_SemicolonKeyword_1_1_q = new TokenAlias(false, true, grammarAccess.getXExpressionInClosureAccess().getSemicolonKeyword_1_1());
		match_XFunctionTypeRef___LeftParenthesisKeyword_0_0_RightParenthesisKeyword_0_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getXFunctionTypeRefAccess().getLeftParenthesisKeyword_0_0()), new TokenAlias(false, false, grammarAccess.getXFunctionTypeRefAccess().getRightParenthesisKeyword_0_2()));
		match_XImportDeclaration_SemicolonKeyword_2_q = new TokenAlias(false, true, grammarAccess.getXImportDeclarationAccess().getSemicolonKeyword_2());
		match_XParenthesizedExpression_LeftParenthesisKeyword_0_a = new TokenAlias(true, true, grammarAccess.getXParenthesizedExpressionAccess().getLeftParenthesisKeyword_0());
		match_XParenthesizedExpression_LeftParenthesisKeyword_0_p = new TokenAlias(true, false, grammarAccess.getXParenthesizedExpressionAccess().getLeftParenthesisKeyword_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if(ruleCall.getRule() == grammarAccess.getArrayBracketsRule())
			return getArrayBracketsToken(semanticObject, ruleCall, node);
		else if(ruleCall.getRule() == grammarAccess.getOpSingleAssignRule())
			return getOpSingleAssignToken(semanticObject, ruleCall, node);
		else if(ruleCall.getRule() == grammarAccess.getSTRINGRule())
			return getSTRINGToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * ArrayBrackets :
	 * 	'[' ']'
	 * ;
	 */
	protected String getArrayBracketsToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "[]";
	}
	
	/**
	 * OpSingleAssign:
	 * 	'='
	 * ;
	 */
	protected String getOpSingleAssignToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "=";
	}
	
	/**
	 * terminal STRING: 
	 * 			'"' ( '\\' .  | !('\\'|'"') )* '"'? |
	 * 			"'" ( '\\' .  | !('\\'|"'") )* "'"?;
	 */
	protected String getSTRINGToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "\"";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if(match_Decision_OptionsKeyword_3_4_0_a.equals(syntax))
				emit_Decision_OptionsKeyword_3_4_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Decision_OptionsKeyword_3_4_0_p.equals(syntax))
				emit_Decision_OptionsKeyword_3_4_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Goal_RightSquareBracketKeyword_2_1_a.equals(syntax))
				emit_Goal_RightSquareBracketKeyword_2_1_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Goal_RightSquareBracketKeyword_2_1_p.equals(syntax))
				emit_Goal_RightSquareBracketKeyword_2_1_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Option_PriorityKeyword_4_3_0_a.equals(syntax))
				emit_Option_PriorityKeyword_4_3_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Option___PriorityKeyword_4_3_0_a_ConflictsKeyword_4_2_0__q.equals(syntax))
				emit_Option___PriorityKeyword_4_3_0_a_ConflictsKeyword_4_2_0__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_Option___PriorityKeyword_4_3_0_a_RefinesKeyword_4_1_0__q.equals(syntax))
				emit_Option___PriorityKeyword_4_3_0_a_RefinesKeyword_4_1_0__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_XBlockExpression_SemicolonKeyword_2_1_q.equals(syntax))
				emit_XBlockExpression_SemicolonKeyword_2_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_XExpressionInClosure_SemicolonKeyword_1_1_q.equals(syntax))
				emit_XExpressionInClosure_SemicolonKeyword_1_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_XFunctionTypeRef___LeftParenthesisKeyword_0_0_RightParenthesisKeyword_0_2__q.equals(syntax))
				emit_XFunctionTypeRef___LeftParenthesisKeyword_0_0_RightParenthesisKeyword_0_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_XImportDeclaration_SemicolonKeyword_2_q.equals(syntax))
				emit_XImportDeclaration_SemicolonKeyword_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_XParenthesizedExpression_LeftParenthesisKeyword_0_a.equals(syntax))
				emit_XParenthesizedExpression_LeftParenthesisKeyword_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_XParenthesizedExpression_LeftParenthesisKeyword_0_p.equals(syntax))
				emit_XParenthesizedExpression_LeftParenthesisKeyword_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     'options:'*
	 *
	 * This ambiguous syntax occurs at:
	 *     due=STRING (ambiguity) ']' (rule end)
	 *     due=STRING (ambiguity) 'due' due=STRING
	 *     due=STRING (ambiguity) 'rationale' rationale=STRING
	 *     due=STRING (ambiguity) 'response measure' response_measure=STRING
	 *     due=STRING (ambiguity) 'responsible' responsible=[Stakeholder|ID]
	 *     name=ID '[' (ambiguity) ']' (rule end)
	 *     name=ID '[' (ambiguity) 'due' due=STRING
	 *     name=ID '[' (ambiguity) 'rationale' rationale=STRING
	 *     name=ID '[' (ambiguity) 'response measure' response_measure=STRING
	 *     name=ID '[' (ambiguity) 'responsible' responsible=[Stakeholder|ID]
	 *     options+=[Option|ID] '}' (ambiguity) ']' (rule end)
	 *     options+=[Option|ID] '}' (ambiguity) 'due' due=STRING
	 *     options+=[Option|ID] '}' (ambiguity) 'rationale' rationale=STRING
	 *     options+=[Option|ID] '}' (ambiguity) 'response measure' response_measure=STRING
	 *     options+=[Option|ID] '}' (ambiguity) 'responsible' responsible=[Stakeholder|ID]
	 *     rationale=STRING (ambiguity) ']' (rule end)
	 *     rationale=STRING (ambiguity) 'due' due=STRING
	 *     rationale=STRING (ambiguity) 'rationale' rationale=STRING
	 *     rationale=STRING (ambiguity) 'response measure' response_measure=STRING
	 *     rationale=STRING (ambiguity) 'responsible' responsible=[Stakeholder|ID]
	 *     response_measure=STRING (ambiguity) ']' (rule end)
	 *     response_measure=STRING (ambiguity) 'due' due=STRING
	 *     response_measure=STRING (ambiguity) 'rationale' rationale=STRING
	 *     response_measure=STRING (ambiguity) 'response measure' response_measure=STRING
	 *     response_measure=STRING (ambiguity) 'responsible' responsible=[Stakeholder|ID]
	 *     responsible=[Stakeholder|ID] (ambiguity) ']' (rule end)
	 *     responsible=[Stakeholder|ID] (ambiguity) 'due' due=STRING
	 *     responsible=[Stakeholder|ID] (ambiguity) 'rationale' rationale=STRING
	 *     responsible=[Stakeholder|ID] (ambiguity) 'response measure' response_measure=STRING
	 *     responsible=[Stakeholder|ID] (ambiguity) 'responsible' responsible=[Stakeholder|ID]
	 */
	protected void emit_Decision_OptionsKeyword_3_4_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'options:'+
	 *
	 * This ambiguous syntax occurs at:
	 *     due=STRING (ambiguity) '{' options+=[Option|ID]
	 *     name=ID '[' (ambiguity) '{' options+=[Option|ID]
	 *     options+=[Option|ID] '}' (ambiguity) '{' options+=[Option|ID]
	 *     rationale=STRING (ambiguity) '{' options+=[Option|ID]
	 *     response_measure=STRING (ambiguity) '{' options+=[Option|ID]
	 *     responsible=[Stakeholder|ID] (ambiguity) '{' options+=[Option|ID]
	 */
	protected void emit_Decision_OptionsKeyword_3_4_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ']'*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) 'Goal' name=QualifiedName
	 *     (rule start) (ambiguity) 'see' 'document' docReference+=STRING
	 *     (rule start) (ambiguity) (rule start)
	 *     (rule start) (ambiguity) rationale=Rationale
	 *     description=Description (ambiguity) 'Goal' name=QualifiedName
	 *     description=Description (ambiguity) 'see' 'document' docReference+=STRING
	 *     description=Description (ambiguity) (rule end)
	 *     description=Description (ambiguity) rationale=Rationale
	 *     name=QualifiedName '[' (ambiguity) 'Goal' name=QualifiedName
	 *     name=QualifiedName '[' (ambiguity) 'see' 'document' docReference+=STRING
	 *     name=QualifiedName '[' (ambiguity) (rule end)
	 *     name=QualifiedName '[' (ambiguity) rationale=Rationale
	 *     rationale=Rationale (ambiguity) 'Goal' name=QualifiedName
	 *     rationale=Rationale (ambiguity) 'see' 'document' docReference+=STRING
	 *     rationale=Rationale (ambiguity) (rule end)
	 *     rationale=Rationale (ambiguity) rationale=Rationale
	 *     superType=[Goal|ID] '[' (ambiguity) 'Goal' name=QualifiedName
	 *     superType=[Goal|ID] '[' (ambiguity) 'see' 'document' docReference+=STRING
	 *     superType=[Goal|ID] '[' (ambiguity) (rule end)
	 *     superType=[Goal|ID] '[' (ambiguity) rationale=Rationale
	 *     title=STRING '[' (ambiguity) 'Goal' name=QualifiedName
	 *     title=STRING '[' (ambiguity) 'see' 'document' docReference+=STRING
	 *     title=STRING '[' (ambiguity) (rule end)
	 *     title=STRING '[' (ambiguity) rationale=Rationale
	 */
	protected void emit_Goal_RightSquareBracketKeyword_2_1_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ']'+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 *     docReference+=STRING (ambiguity) 'Goal' name=QualifiedName
	 *     docReference+=STRING (ambiguity) 'see' 'document' docReference+=STRING
	 *     docReference+=STRING (ambiguity) (rule end)
	 *     docReference+=STRING (ambiguity) rationale=Rationale
	 */
	protected void emit_Goal_RightSquareBracketKeyword_2_1_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'priority'*
	 *
	 * This ambiguous syntax occurs at:
	 *     cod=INT (ambiguity) ']' (rule end)
	 *     cod=INT (ambiguity) 'completion' date=STRING
	 *     cod=INT (ambiguity) 'conflicts' conflictsReference+=[IntentionalElement|ID]
	 *     cod=INT (ambiguity) 'cost' cost=INT
	 *     cod=INT (ambiguity) 'delay cost' cod=INT
	 *     cod=INT (ambiguity) 'refines' refinesReference+=[IntentionalElement|ID]
	 *     cod=INT (ambiguity) 'time' time=INT
	 *     cod=INT (ambiguity) description=Description
	 *     cod=INT (ambiguity) priority=PriorityEnum
	 *     conflictsReference+=[IntentionalElement|ID] (ambiguity) ']' (rule end)
	 *     conflictsReference+=[IntentionalElement|ID] (ambiguity) 'completion' date=STRING
	 *     conflictsReference+=[IntentionalElement|ID] (ambiguity) 'cost' cost=INT
	 *     conflictsReference+=[IntentionalElement|ID] (ambiguity) 'delay cost' cod=INT
	 *     conflictsReference+=[IntentionalElement|ID] (ambiguity) 'refines' refinesReference+=[IntentionalElement|ID]
	 *     conflictsReference+=[IntentionalElement|ID] (ambiguity) 'time' time=INT
	 *     conflictsReference+=[IntentionalElement|ID] (ambiguity) description=Description
	 *     conflictsReference+=[IntentionalElement|ID] (ambiguity) priority=PriorityEnum
	 *     cost=INT (ambiguity) ']' (rule end)
	 *     cost=INT (ambiguity) 'completion' date=STRING
	 *     cost=INT (ambiguity) 'conflicts' conflictsReference+=[IntentionalElement|ID]
	 *     cost=INT (ambiguity) 'cost' cost=INT
	 *     cost=INT (ambiguity) 'delay cost' cod=INT
	 *     cost=INT (ambiguity) 'refines' refinesReference+=[IntentionalElement|ID]
	 *     cost=INT (ambiguity) 'time' time=INT
	 *     cost=INT (ambiguity) description=Description
	 *     cost=INT (ambiguity) priority=PriorityEnum
	 *     date=STRING (ambiguity) ']' (rule end)
	 *     date=STRING (ambiguity) 'completion' date=STRING
	 *     date=STRING (ambiguity) 'conflicts' conflictsReference+=[IntentionalElement|ID]
	 *     date=STRING (ambiguity) 'cost' cost=INT
	 *     date=STRING (ambiguity) 'delay cost' cod=INT
	 *     date=STRING (ambiguity) 'refines' refinesReference+=[IntentionalElement|ID]
	 *     date=STRING (ambiguity) 'time' time=INT
	 *     date=STRING (ambiguity) description=Description
	 *     date=STRING (ambiguity) priority=PriorityEnum
	 *     description=Description (ambiguity) ']' (rule end)
	 *     description=Description (ambiguity) 'completion' date=STRING
	 *     description=Description (ambiguity) 'conflicts' conflictsReference+=[IntentionalElement|ID]
	 *     description=Description (ambiguity) 'cost' cost=INT
	 *     description=Description (ambiguity) 'delay cost' cod=INT
	 *     description=Description (ambiguity) 'refines' refinesReference+=[IntentionalElement|ID]
	 *     description=Description (ambiguity) 'time' time=INT
	 *     description=Description (ambiguity) description=Description
	 *     description=Description (ambiguity) priority=PriorityEnum
	 *     name=QualifiedName '[' (ambiguity) ']' (rule end)
	 *     name=QualifiedName '[' (ambiguity) 'completion' date=STRING
	 *     name=QualifiedName '[' (ambiguity) 'conflicts' conflictsReference+=[IntentionalElement|ID]
	 *     name=QualifiedName '[' (ambiguity) 'cost' cost=INT
	 *     name=QualifiedName '[' (ambiguity) 'delay cost' cod=INT
	 *     name=QualifiedName '[' (ambiguity) 'refines' refinesReference+=[IntentionalElement|ID]
	 *     name=QualifiedName '[' (ambiguity) 'time' time=INT
	 *     name=QualifiedName '[' (ambiguity) description=Description
	 *     name=QualifiedName '[' (ambiguity) priority=PriorityEnum
	 *     priority=PriorityEnum (ambiguity) ']' (rule end)
	 *     priority=PriorityEnum (ambiguity) 'completion' date=STRING
	 *     priority=PriorityEnum (ambiguity) 'conflicts' conflictsReference+=[IntentionalElement|ID]
	 *     priority=PriorityEnum (ambiguity) 'cost' cost=INT
	 *     priority=PriorityEnum (ambiguity) 'delay cost' cod=INT
	 *     priority=PriorityEnum (ambiguity) 'refines' refinesReference+=[IntentionalElement|ID]
	 *     priority=PriorityEnum (ambiguity) 'time' time=INT
	 *     priority=PriorityEnum (ambiguity) description=Description
	 *     priority=PriorityEnum (ambiguity) priority=PriorityEnum
	 *     refinesReference+=[IntentionalElement|ID] (ambiguity) ']' (rule end)
	 *     refinesReference+=[IntentionalElement|ID] (ambiguity) 'completion' date=STRING
	 *     refinesReference+=[IntentionalElement|ID] (ambiguity) 'conflicts' conflictsReference+=[IntentionalElement|ID]
	 *     refinesReference+=[IntentionalElement|ID] (ambiguity) 'cost' cost=INT
	 *     refinesReference+=[IntentionalElement|ID] (ambiguity) 'delay cost' cod=INT
	 *     refinesReference+=[IntentionalElement|ID] (ambiguity) 'time' time=INT
	 *     refinesReference+=[IntentionalElement|ID] (ambiguity) description=Description
	 *     refinesReference+=[IntentionalElement|ID] (ambiguity) priority=PriorityEnum
	 *     time=INT (ambiguity) ']' (rule end)
	 *     time=INT (ambiguity) 'completion' date=STRING
	 *     time=INT (ambiguity) 'conflicts' conflictsReference+=[IntentionalElement|ID]
	 *     time=INT (ambiguity) 'cost' cost=INT
	 *     time=INT (ambiguity) 'delay cost' cod=INT
	 *     time=INT (ambiguity) 'refines' refinesReference+=[IntentionalElement|ID]
	 *     time=INT (ambiguity) 'time' time=INT
	 *     time=INT (ambiguity) description=Description
	 *     time=INT (ambiguity) priority=PriorityEnum
	 *     title=STRING '[' (ambiguity) ']' (rule end)
	 *     title=STRING '[' (ambiguity) 'completion' date=STRING
	 *     title=STRING '[' (ambiguity) 'conflicts' conflictsReference+=[IntentionalElement|ID]
	 *     title=STRING '[' (ambiguity) 'cost' cost=INT
	 *     title=STRING '[' (ambiguity) 'delay cost' cod=INT
	 *     title=STRING '[' (ambiguity) 'refines' refinesReference+=[IntentionalElement|ID]
	 *     title=STRING '[' (ambiguity) 'time' time=INT
	 *     title=STRING '[' (ambiguity) description=Description
	 *     title=STRING '[' (ambiguity) priority=PriorityEnum
	 */
	protected void emit_Option_PriorityKeyword_4_3_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('priority'* 'conflicts')?
	 *
	 * This ambiguous syntax occurs at:
	 *     conflictsReference+=[IntentionalElement|ID] (ambiguity) conflictsReference+=[IntentionalElement|ID]
	 */
	protected void emit_Option___PriorityKeyword_4_3_0_a_ConflictsKeyword_4_2_0__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('priority'* 'refines')?
	 *
	 * This ambiguous syntax occurs at:
	 *     refinesReference+=[IntentionalElement|ID] (ambiguity) refinesReference+=[IntentionalElement|ID]
	 */
	protected void emit_Option___PriorityKeyword_4_3_0_a_RefinesKeyword_4_1_0__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ';'?
	 *
	 * This ambiguous syntax occurs at:
	 *     expressions+=XExpressionOrVarDeclaration (ambiguity) '}' ')' (rule end)
	 *     expressions+=XExpressionOrVarDeclaration (ambiguity) '}' (rule end)
	 *     expressions+=XExpressionOrVarDeclaration (ambiguity) expressions+=XExpressionOrVarDeclaration
	 */
	protected void emit_XBlockExpression_SemicolonKeyword_2_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ';'?
	 *
	 * This ambiguous syntax occurs at:
	 *     expressions+=XExpressionOrVarDeclaration (ambiguity) (rule end)
	 *     expressions+=XExpressionOrVarDeclaration (ambiguity) expressions+=XExpressionOrVarDeclaration
	 */
	protected void emit_XExpressionInClosure_SemicolonKeyword_1_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('(' ')')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '=>' returnType=JvmTypeReference
	 */
	protected void emit_XFunctionTypeRef___LeftParenthesisKeyword_0_0_RightParenthesisKeyword_0_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ';'?
	 *
	 * This ambiguous syntax occurs at:
	 *     importedNamespace=QualifiedNameWithWildcard (ambiguity) (rule end)
	 *     importedType=[JvmDeclaredType|QualifiedName] (ambiguity) (rule end)
	 *     memberName=ValidID (ambiguity) (rule end)
	 *     wildcard?='*' (ambiguity) (rule end)
	 */
	protected void emit_XImportDeclaration_SemicolonKeyword_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '('*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '#' '[' ']' (rule start)
	 *     (rule start) (ambiguity) '#' '[' elements+=XExpression
	 *     (rule start) (ambiguity) '#' '{' '}' (rule start)
	 *     (rule start) (ambiguity) '#' '{' elements+=XExpression
	 *     (rule start) (ambiguity) '<' typeArguments+=JvmArgumentTypeReference
	 *     (rule start) (ambiguity) '[' declaredFormalParameters+=JvmFormalParameter
	 *     (rule start) (ambiguity) '[' explicitSyntax?='|'
	 *     (rule start) (ambiguity) '[' expression=XExpressionInClosure
	 *     (rule start) (ambiguity) 'do' body=XExpression
	 *     (rule start) (ambiguity) 'false' (rule start)
	 *     (rule start) (ambiguity) 'for' '(' ';' ';' ')' eachExpression=XExpression
	 *     (rule start) (ambiguity) 'for' '(' ';' ';' updateExpressions+=XExpression
	 *     (rule start) (ambiguity) 'for' '(' ';' expression=XExpression
	 *     (rule start) (ambiguity) 'for' '(' declaredParam=JvmFormalParameter
	 *     (rule start) (ambiguity) 'for' '(' initExpressions+=XExpressionOrVarDeclaration
	 *     (rule start) (ambiguity) 'if' '(' if=XExpression
	 *     (rule start) (ambiguity) 'new' constructor=[JvmConstructor|QualifiedName]
	 *     (rule start) (ambiguity) 'null' (rule start)
	 *     (rule start) (ambiguity) 'return' (rule start)
	 *     (rule start) (ambiguity) 'return' expression=XExpression
	 *     (rule start) (ambiguity) 'switch' '(' declaredParam=JvmFormalParameter
	 *     (rule start) (ambiguity) 'switch' declaredParam=JvmFormalParameter
	 *     (rule start) (ambiguity) 'switch' switch=XExpression
	 *     (rule start) (ambiguity) 'synchronized' '(' param=XExpression
	 *     (rule start) (ambiguity) 'throw' expression=XExpression
	 *     (rule start) (ambiguity) 'try' expression=XExpression
	 *     (rule start) (ambiguity) 'typeof' '(' type=[JvmType|QualifiedName]
	 *     (rule start) (ambiguity) 'while' '(' predicate=XExpression
	 *     (rule start) (ambiguity) '{' '}' (rule start)
	 *     (rule start) (ambiguity) '{' expressions+=XExpressionOrVarDeclaration
	 *     (rule start) (ambiguity) feature=[JvmIdentifiableElement|FeatureCallID]
	 *     (rule start) (ambiguity) feature=[JvmIdentifiableElement|IdOrSuper]
	 *     (rule start) (ambiguity) feature=[JvmIdentifiableElement|OpUnary]
	 *     (rule start) (ambiguity) isTrue?='true'
	 *     (rule start) (ambiguity) value=Number
	 *     (rule start) (ambiguity) value=STRING
	 *     (rule start) (ambiguity) {XAssignment.assignable=}
	 *     (rule start) (ambiguity) {XBinaryOperation.leftOperand=}
	 *     (rule start) (ambiguity) {XCastedExpression.target=}
	 *     (rule start) (ambiguity) {XInstanceOfExpression.expression=}
	 *     (rule start) (ambiguity) {XMemberFeatureCall.memberCallTarget=}
	 *     (rule start) (ambiguity) {XPostfixOperation.operand=}
	 */
	protected void emit_XParenthesizedExpression_LeftParenthesisKeyword_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '('+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '#' '[' ']' ')' (rule start)
	 *     (rule start) (ambiguity) '#' '[' elements+=XExpression
	 *     (rule start) (ambiguity) '#' '{' '}' ')' (rule start)
	 *     (rule start) (ambiguity) '#' '{' elements+=XExpression
	 *     (rule start) (ambiguity) '<' typeArguments+=JvmArgumentTypeReference
	 *     (rule start) (ambiguity) '[' declaredFormalParameters+=JvmFormalParameter
	 *     (rule start) (ambiguity) '[' explicitSyntax?='|'
	 *     (rule start) (ambiguity) '[' expression=XExpressionInClosure
	 *     (rule start) (ambiguity) 'do' body=XExpression
	 *     (rule start) (ambiguity) 'false' ')' (rule start)
	 *     (rule start) (ambiguity) 'for' '(' ';' ';' ')' eachExpression=XExpression
	 *     (rule start) (ambiguity) 'for' '(' ';' ';' updateExpressions+=XExpression
	 *     (rule start) (ambiguity) 'for' '(' ';' expression=XExpression
	 *     (rule start) (ambiguity) 'for' '(' declaredParam=JvmFormalParameter
	 *     (rule start) (ambiguity) 'for' '(' initExpressions+=XExpressionOrVarDeclaration
	 *     (rule start) (ambiguity) 'if' '(' if=XExpression
	 *     (rule start) (ambiguity) 'new' constructor=[JvmConstructor|QualifiedName]
	 *     (rule start) (ambiguity) 'null' ')' (rule start)
	 *     (rule start) (ambiguity) 'return' ')' (rule start)
	 *     (rule start) (ambiguity) 'return' expression=XExpression
	 *     (rule start) (ambiguity) 'switch' '(' declaredParam=JvmFormalParameter
	 *     (rule start) (ambiguity) 'switch' declaredParam=JvmFormalParameter
	 *     (rule start) (ambiguity) 'switch' switch=XExpression
	 *     (rule start) (ambiguity) 'synchronized' '(' param=XExpression
	 *     (rule start) (ambiguity) 'throw' expression=XExpression
	 *     (rule start) (ambiguity) 'try' expression=XExpression
	 *     (rule start) (ambiguity) 'typeof' '(' type=[JvmType|QualifiedName]
	 *     (rule start) (ambiguity) 'while' '(' predicate=XExpression
	 *     (rule start) (ambiguity) '{' '}' ')' (rule start)
	 *     (rule start) (ambiguity) '{' expressions+=XExpressionOrVarDeclaration
	 *     (rule start) (ambiguity) feature=[JvmIdentifiableElement|FeatureCallID]
	 *     (rule start) (ambiguity) feature=[JvmIdentifiableElement|IdOrSuper]
	 *     (rule start) (ambiguity) feature=[JvmIdentifiableElement|OpUnary]
	 *     (rule start) (ambiguity) isTrue?='true'
	 *     (rule start) (ambiguity) value=Number
	 *     (rule start) (ambiguity) value=STRING
	 *     (rule start) (ambiguity) {XAssignment.assignable=}
	 *     (rule start) (ambiguity) {XBinaryOperation.leftOperand=}
	 *     (rule start) (ambiguity) {XCastedExpression.target=}
	 *     (rule start) (ambiguity) {XInstanceOfExpression.expression=}
	 *     (rule start) (ambiguity) {XMemberFeatureCall.memberCallTarget=}
	 *     (rule start) (ambiguity) {XPostfixOperation.operand=}
	 */
	protected void emit_XParenthesizedExpression_LeftParenthesisKeyword_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
