/*
 * generated by Xtext
 */
package edu.cmu.sei.eebm.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import edu.cmu.sei.eebm.services.EEBMGrammarAccess;

public class EEBMParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private EEBMGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected edu.cmu.sei.eebm.parser.antlr.internal.InternalEEBMParser createParser(XtextTokenStream stream) {
		return new edu.cmu.sei.eebm.parser.antlr.internal.InternalEEBMParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Roadmap";
	}
	
	public EEBMGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EEBMGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
