/**
 * generated by Xtext
 */
package edu.cmu.sei.eebm.validation;

import edu.cmu.sei.eebm.validation.AbstractEEBMValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class EEBMValidator extends AbstractEEBMValidator {
}
