/*
 * generated by Xtext
 */
package edu.cmu.sei.eebm.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import edu.cmu.sei.eebm.services.EEBMGrammarAccess;

public class EEBMParser extends AbstractContentAssistParser {
	
	@Inject
	private EEBMGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected edu.cmu.sei.eebm.ui.contentassist.antlr.internal.InternalEEBMParser createParser() {
		edu.cmu.sei.eebm.ui.contentassist.antlr.internal.InternalEEBMParser result = new edu.cmu.sei.eebm.ui.contentassist.antlr.internal.InternalEEBMParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getRoadmapAccess().getRelationsAlternatives_2_0(), "rule__Roadmap__RelationsAlternatives_2_0");
					put(grammarAccess.getIntentionalElementAccess().getAlternatives(), "rule__IntentionalElement__Alternatives");
					put(grammarAccess.getRefinementAccess().getAlternatives(), "rule__Refinement__Alternatives");
					put(grammarAccess.getPriorityEnumAccess().getAlternatives(), "rule__PriorityEnum__Alternatives");
					put(grammarAccess.getRoadmapAccess().getGroup(), "rule__Roadmap__Group__0");
					put(grammarAccess.getRoadmapAccess().getGroup_0(), "rule__Roadmap__Group_0__0");
					put(grammarAccess.getAndRefinementAccess().getGroup(), "rule__AndRefinement__Group__0");
					put(grammarAccess.getAndRefinementAccess().getGroup_3_0(), "rule__AndRefinement__Group_3_0__0");
					put(grammarAccess.getAndRefinementAccess().getGroup_3_1(), "rule__AndRefinement__Group_3_1__0");
					put(grammarAccess.getAndRefinementAccess().getGroup_3_1_3(), "rule__AndRefinement__Group_3_1_3__0");
					put(grammarAccess.getOrRefinementAccess().getGroup(), "rule__OrRefinement__Group__0");
					put(grammarAccess.getOrRefinementAccess().getGroup_3_0(), "rule__OrRefinement__Group_3_0__0");
					put(grammarAccess.getOrRefinementAccess().getGroup_3_1(), "rule__OrRefinement__Group_3_1__0");
					put(grammarAccess.getOrRefinementAccess().getGroup_3_1_3(), "rule__OrRefinement__Group_3_1_3__0");
					put(grammarAccess.getConflictAccess().getGroup(), "rule__Conflict__Group__0");
					put(grammarAccess.getConflictAccess().getGroup_3_0(), "rule__Conflict__Group_3_0__0");
					put(grammarAccess.getConflictAccess().getGroup_3_1(), "rule__Conflict__Group_3_1__0");
					put(grammarAccess.getGoalAccess().getGroup_0(), "rule__Goal__Group_0__0");
					put(grammarAccess.getGoalAccess().getGroup_0_2(), "rule__Goal__Group_0_2__0");
					put(grammarAccess.getGoalAccess().getGroup_2(), "rule__Goal__Group_2__0");
					put(grammarAccess.getGoalAccess().getGroup_3(), "rule__Goal__Group_3__0");
					put(grammarAccess.getGoalAccess().getGroup_4(), "rule__Goal__Group_4__0");
					put(grammarAccess.getGoalAccess().getGroup_5(), "rule__Goal__Group_5__0");
					put(grammarAccess.getGoalAccess().getGroup_6(), "rule__Goal__Group_6__0");
					put(grammarAccess.getGoalAccess().getGroup_8(), "rule__Goal__Group_8__0");
					put(grammarAccess.getSoftgoalAccess().getGroup_0(), "rule__Softgoal__Group_0__0");
					put(grammarAccess.getSoftgoalAccess().getGroup_0_2(), "rule__Softgoal__Group_0_2__0");
					put(grammarAccess.getSoftgoalAccess().getGroup_2(), "rule__Softgoal__Group_2__0");
					put(grammarAccess.getSoftgoalAccess().getGroup_3(), "rule__Softgoal__Group_3__0");
					put(grammarAccess.getSoftgoalAccess().getGroup_4(), "rule__Softgoal__Group_4__0");
					put(grammarAccess.getSoftgoalAccess().getGroup_5(), "rule__Softgoal__Group_5__0");
					put(grammarAccess.getSoftgoalAccess().getGroup_6(), "rule__Softgoal__Group_6__0");
					put(grammarAccess.getSoftgoalAccess().getGroup_8(), "rule__Softgoal__Group_8__0");
					put(grammarAccess.getTaskAccess().getGroup_0(), "rule__Task__Group_0__0");
					put(grammarAccess.getTaskAccess().getGroup_0_2(), "rule__Task__Group_0_2__0");
					put(grammarAccess.getTaskAccess().getGroup_2(), "rule__Task__Group_2__0");
					put(grammarAccess.getTaskAccess().getGroup_3(), "rule__Task__Group_3__0");
					put(grammarAccess.getTaskAccess().getGroup_4(), "rule__Task__Group_4__0");
					put(grammarAccess.getTaskAccess().getGroup_5(), "rule__Task__Group_5__0");
					put(grammarAccess.getTaskAccess().getGroup_6(), "rule__Task__Group_6__0");
					put(grammarAccess.getTaskAccess().getGroup_6_0(), "rule__Task__Group_6_0__0");
					put(grammarAccess.getDescriptionAccess().getGroup(), "rule__Description__Group__0");
					put(grammarAccess.getRationaleAccess().getGroup(), "rule__Rationale__Group__0");
					put(grammarAccess.getReferenceAccess().getGroup(), "rule__Reference__Group__0");
					put(grammarAccess.getPreferenceAccess().getGroup(), "rule__Preference__Group__0");
					put(grammarAccess.getRoadmapAccess().getNameAssignment_0_0(), "rule__Roadmap__NameAssignment_0_0");
					put(grammarAccess.getRoadmapAccess().getComponentsAssignment_1(), "rule__Roadmap__ComponentsAssignment_1");
					put(grammarAccess.getRoadmapAccess().getRelationsAssignment_2(), "rule__Roadmap__RelationsAssignment_2");
					put(grammarAccess.getAndRefinementAccess().getNameAssignment_1(), "rule__AndRefinement__NameAssignment_1");
					put(grammarAccess.getAndRefinementAccess().getDestAssignment_3_0_1(), "rule__AndRefinement__DestAssignment_3_0_1");
					put(grammarAccess.getAndRefinementAccess().getSourceAssignment_3_1_2(), "rule__AndRefinement__SourceAssignment_3_1_2");
					put(grammarAccess.getAndRefinementAccess().getSourceAssignment_3_1_3_1(), "rule__AndRefinement__SourceAssignment_3_1_3_1");
					put(grammarAccess.getOrRefinementAccess().getNameAssignment_1(), "rule__OrRefinement__NameAssignment_1");
					put(grammarAccess.getOrRefinementAccess().getDestAssignment_3_0_1(), "rule__OrRefinement__DestAssignment_3_0_1");
					put(grammarAccess.getOrRefinementAccess().getSourceAssignment_3_1_2(), "rule__OrRefinement__SourceAssignment_3_1_2");
					put(grammarAccess.getOrRefinementAccess().getSourceAssignment_3_1_3_1(), "rule__OrRefinement__SourceAssignment_3_1_3_1");
					put(grammarAccess.getConflictAccess().getNameAssignment_1(), "rule__Conflict__NameAssignment_1");
					put(grammarAccess.getConflictAccess().getSourceAssignment_3_0_1(), "rule__Conflict__SourceAssignment_3_0_1");
					put(grammarAccess.getConflictAccess().getDestAssignment_3_1_1(), "rule__Conflict__DestAssignment_3_1_1");
					put(grammarAccess.getGoalAccess().getNameAssignment_0_1(), "rule__Goal__NameAssignment_0_1");
					put(grammarAccess.getGoalAccess().getTitleAssignment_0_2_1(), "rule__Goal__TitleAssignment_0_2_1");
					put(grammarAccess.getGoalAccess().getDescriptionAssignment_0_4(), "rule__Goal__DescriptionAssignment_0_4");
					put(grammarAccess.getGoalAccess().getPriorityAssignment_1_1(), "rule__Goal__PriorityAssignment_1_1");
					put(grammarAccess.getGoalAccess().getTimeAssignment_2_1(), "rule__Goal__TimeAssignment_2_1");
					put(grammarAccess.getGoalAccess().getCostAssignment_3_1(), "rule__Goal__CostAssignment_3_1");
					put(grammarAccess.getGoalAccess().getBenefitAssignment_4_1(), "rule__Goal__BenefitAssignment_4_1");
					put(grammarAccess.getGoalAccess().getDateAssignment_5_1(), "rule__Goal__DateAssignment_5_1");
					put(grammarAccess.getGoalAccess().getCodAssignment_6_1(), "rule__Goal__CodAssignment_6_1");
					put(grammarAccess.getGoalAccess().getRationaleAssignment_7(), "rule__Goal__RationaleAssignment_7");
					put(grammarAccess.getGoalAccess().getRefAssignment_8_0(), "rule__Goal__RefAssignment_8_0");
					put(grammarAccess.getSoftgoalAccess().getNameAssignment_0_1(), "rule__Softgoal__NameAssignment_0_1");
					put(grammarAccess.getSoftgoalAccess().getTitleAssignment_0_2_1(), "rule__Softgoal__TitleAssignment_0_2_1");
					put(grammarAccess.getSoftgoalAccess().getDescriptionAssignment_0_4(), "rule__Softgoal__DescriptionAssignment_0_4");
					put(grammarAccess.getSoftgoalAccess().getPriorityAssignment_1_1(), "rule__Softgoal__PriorityAssignment_1_1");
					put(grammarAccess.getSoftgoalAccess().getTimeAssignment_2_1(), "rule__Softgoal__TimeAssignment_2_1");
					put(grammarAccess.getSoftgoalAccess().getCostAssignment_3_1(), "rule__Softgoal__CostAssignment_3_1");
					put(grammarAccess.getSoftgoalAccess().getBenefitAssignment_4_1(), "rule__Softgoal__BenefitAssignment_4_1");
					put(grammarAccess.getSoftgoalAccess().getDateAssignment_5_1(), "rule__Softgoal__DateAssignment_5_1");
					put(grammarAccess.getSoftgoalAccess().getCodAssignment_6_1(), "rule__Softgoal__CodAssignment_6_1");
					put(grammarAccess.getSoftgoalAccess().getRationaleAssignment_7(), "rule__Softgoal__RationaleAssignment_7");
					put(grammarAccess.getSoftgoalAccess().getRefAssignment_8_0(), "rule__Softgoal__RefAssignment_8_0");
					put(grammarAccess.getTaskAccess().getNameAssignment_0_1(), "rule__Task__NameAssignment_0_1");
					put(grammarAccess.getTaskAccess().getTitleAssignment_0_2_1(), "rule__Task__TitleAssignment_0_2_1");
					put(grammarAccess.getTaskAccess().getDescriptionAssignment_0_4(), "rule__Task__DescriptionAssignment_0_4");
					put(grammarAccess.getTaskAccess().getPriorityAssignment_1_1(), "rule__Task__PriorityAssignment_1_1");
					put(grammarAccess.getTaskAccess().getTimeAssignment_2_1(), "rule__Task__TimeAssignment_2_1");
					put(grammarAccess.getTaskAccess().getCostAssignment_3_1(), "rule__Task__CostAssignment_3_1");
					put(grammarAccess.getTaskAccess().getBenefitAssignment_4_1(), "rule__Task__BenefitAssignment_4_1");
					put(grammarAccess.getTaskAccess().getDateAssignment_5_1(), "rule__Task__DateAssignment_5_1");
					put(grammarAccess.getTaskAccess().getCodAssignment_6_0_1(), "rule__Task__CodAssignment_6_0_1");
					put(grammarAccess.getDescriptionAccess().getTextAssignment_1(), "rule__Description__TextAssignment_1");
					put(grammarAccess.getRationaleAccess().getTextAssignment_1(), "rule__Rationale__TextAssignment_1");
					put(grammarAccess.getReferenceAccess().getDocReferenceAssignment_1(), "rule__Reference__DocReferenceAssignment_1");
					put(grammarAccess.getPreferenceAccess().getFirstAssignment_1(), "rule__Preference__FirstAssignment_1");
					put(grammarAccess.getPreferenceAccess().getLastAssignment_3(), "rule__Preference__LastAssignment_3");
					put(grammarAccess.getAndRefinementAccess().getUnorderedGroup_3(), "rule__AndRefinement__UnorderedGroup_3");
					put(grammarAccess.getOrRefinementAccess().getUnorderedGroup_3(), "rule__OrRefinement__UnorderedGroup_3");
					put(grammarAccess.getConflictAccess().getUnorderedGroup_3(), "rule__Conflict__UnorderedGroup_3");
					put(grammarAccess.getGoalAccess().getUnorderedGroup(), "rule__Goal__UnorderedGroup");
					put(grammarAccess.getGoalAccess().getUnorderedGroup_1(), "rule__Goal__UnorderedGroup_1");
					put(grammarAccess.getSoftgoalAccess().getUnorderedGroup(), "rule__Softgoal__UnorderedGroup");
					put(grammarAccess.getSoftgoalAccess().getUnorderedGroup_1(), "rule__Softgoal__UnorderedGroup_1");
					put(grammarAccess.getTaskAccess().getUnorderedGroup(), "rule__Task__UnorderedGroup");
					put(grammarAccess.getTaskAccess().getUnorderedGroup_1(), "rule__Task__UnorderedGroup_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			edu.cmu.sei.eebm.ui.contentassist.antlr.internal.InternalEEBMParser typedParser = (edu.cmu.sei.eebm.ui.contentassist.antlr.internal.InternalEEBMParser) parser;
			typedParser.entryRuleRoadmap();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public EEBMGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EEBMGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
