/*
 * generated by Xtext
 */
package edu.cmu.sei.eebm.ui.contentassist

import edu.cmu.sei.eebm.ui.contentassist.AbstractEEBMProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class EEBMProposalProvider extends AbstractEEBMProposalProvider {
}
