/*
 * generated by Xtext
 */
package edu.cmu.sei.eebm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EEBMUiModule extends edu.cmu.sei.eebm.ui.AbstractEEBMUiModule {
	public EEBMUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
